### ISSUE TITLE
Use wireplumber c api to activate/deactivate audio stream output 

### ISSUE THREAD

**Issue by fabriziodidomenico1** [PipeWire/wireplumber#1]
Hello to everyone,

i'm currently working on a project that involves the wireplumber's api to interact with different audio video streaming.

At the moment i have different policies that define different media.roles and i'm able to retrieve information of Stream/Output node (ex: a gstreamer based application) using the wp_object_manager and i can play a single audio source at time based on his priority.

What i want to ask is: 

if i have two audio application that use the pipewiresink with the same media.role (so the same priority), how can i suspend and resume their audio streams using the available c api?

Thank you for you help and your work

Fabrizio

**Comment by ford-prefect** [comment]
Hey @fabriziodidomenico1, this is just meant to be a mirror repo, so you'd be better off asking on https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues or asking on IRC (OFTC, #pipewire) or Matrix (#pipewire:matrix.org).
