### ISSUE TITLE
Automaticaly activate hotplugged device as default source/sink and move all streams to it

### ISSUE THREAD

**Issue by Harvie** [PipeWire/wireplumber#11]
When i connect bluetooth headset to my laptop, i have to manualy switch to it. Is there some way to configure wireplumber so it automaticaly switches over to whatever device was recently plugged in?

**Comment by Harvie** [comment]
I think this had solved my issue even better:

WirePlumber 0.4.12[](https://pipewire.pages.freedesktop.org/wireplumber/releases.html#wireplumber-0-4-12)

Changes:

        WirePlumber now maintains a stack of previously configured default nodes and prioritizes to one of those when the actively configured default node becomes unavailable, before calculating the next default using priorities (see !396)

**Comment by Harvie** [comment]
But it only seems to work 1st time after restarting wireplumber, and then it fails again...

**Comment by Harvie** [comment]
Why don't you disable issues in repo settings (or make it read only) then? Instead of telling everyone separately...

**Comment by ford-prefect** [comment]
When we first set this up, there was no option to do this. We might still prefer to leave this open, as folks such as yourself might not notice the pointer to fd.o in the About section, and it might be better for us to see a report and redirect than for users to think there is no issue reporting.

**Comment by ford-prefect** [comment]
I've filed and pinned an informational issue instead.

**Comment by ford-prefect** [comment]
@gkiagia let me know if you'd like to just disable issues instead.

**Comment by gkiagia** [comment]
@ford-prefect yes, please disable issues here. I am not watching them, unless I am pinged.

**Comment by gkiagia** [comment]
@ford-prefect actually, I just understood what you meant by "informational issue"... let's leave it like that and see if we still get reports here

**Comment by Harvie** [comment]
In fact, you can set issues on github as moderated/readonly

**Comment by ford-prefect** [comment]
I believe moderation would be bot-based. I'm okay to leave this as is, and if we have too much more activity, I'll close it down.
