### ISSUE TITLE
Won't get Wireplumber to working sway (fedora 39)

### ISSUE THREAD

**Issue by dxdye** [PipeWire/wireplumber#13]
I've build this.

when I do wpctl status, I get this: 

wpctl: symbol lookup error: /lib64/libwireplumber-0.5.so.0: undefined symbol: pw_log_set_level_string

Don't know how to fix this.

Appendix:
he Meson build system
Version: 1.3.2
Source dir: /home/tw/Programme/wireplumber
Build dir: /home/tw/Programme/wireplumber/build
Build type: native build
Project name: wireplumber
Project version: 0.5.2
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20240316 (Red Hat 13.2.1-7)")
C linker for the host machine: cc ld.bfd 2.40-14
Host machine cpu family: x86_64
Host machine cpu: x86_64
Dependency glib-2.0 found: YES 2.78.3 (cached)
Dependency gobject-2.0 found: YES 2.78.3 (cached)
Dependency gmodule-2.0 found: YES 2.78.3 (cached)
Dependency gio-2.0 found: YES 2.78.3 (cached)
Dependency gio-unix-2.0 found: YES 2.78.3 (cached)
Dependency libspa-0.2 found: YES 0.2 (cached)
Dependency libpipewire-0.3 found: YES 1.1.0 (cached)
Library m found: YES
Dependency threads found: YES unknown (cached)
Dependency intl found: YES unknown (cached)

Executing subproject lua 

lua| Project name: lua-5.4
lua| Project version: 5.4.4
lua| C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20240316 (Red Hat 13.2.1-7)")
lua| C linker for the host machine: cc ld.bfd 2.40-14
lua| Library m found: YES
lua| Build targets in project: 3
lua| Subproject lua finished.

Dependency systemd found: YES 254 (cached)
Dependency libsystemd found: YES 254 (cached)
Dependency libelogind found: YES 255 (cached)
Compiler for C supports arguments -fvisibility=hidden: YES (cached)
Compiler for C supports arguments -Wsuggest-attribute=format: YES (cached)
Compiler for C supports arguments -Wsign-compare: YES (cached)
Compiler for C supports arguments -Wpointer-arith: YES (cached)
Compiler for C supports arguments -Wpointer-sign: YES (cached)
Compiler for C supports arguments -Wformat: YES (cached)
Compiler for C supports arguments -Wformat-security: YES (cached)
Compiler for C supports arguments -Wimplicit-fallthrough: YES (cached)
Compiler for C supports arguments -Wmissing-braces: YES (cached)
Compiler for C supports arguments -Wtype-limits: YES (cached)
Compiler for C supports arguments -Wvariadic-macros: YES (cached)
Compiler for C supports arguments -Wno-missing-field-initializers: YES (cached)
Compiler for C supports arguments -Wno-unused-parameter: YES (cached)
Compiler for C supports arguments -Wno-pedantic: YES (cached)
Compiler for C supports arguments -Wold-style-declaration: YES (cached)
Compiler for C supports arguments -Wunused-result: YES (cached)
Dependency glib-2.0 found: YES 2.78.3 (cached)
Program /usr/bin/glib-mkenums found: YES (/usr/bin/glib-mkenums)
Dependency glib-2.0 found: YES 2.78.3 (cached)
Program /usr/bin/glib-mkenums found: YES (/usr/bin/glib-mkenums)
Configuring wpversion.h using configuration
Configuring wpbuildbasedirs.h using configuration
Found pkg-config: YES (/usr/bin/pkg-config) 1.9.5
Dependency glib-2.0 found: YES 2.78.3 (cached)
Program /usr/bin/glib-mkenums found: YES (/usr/bin/glib-mkenums)
Dependency glib-2.0 found: YES 2.78.3 (cached)
Program /usr/bin/glib-mkenums found: YES (/usr/bin/glib-mkenums)
Dependency gio-2.0 found: YES 2.78.3 (cached)
Program /usr/bin/gdbus-codegen found: YES (/usr/bin/gdbus-codegen)
Dependency glib-2.0 found: YES 2.78.3 (cached)
Program /usr/bin/glib-mkenums found: YES (/usr/bin/glib-mkenums)
Dependency glib-2.0 found: YES 2.78.3 (cached)
Program /usr/bin/glib-mkenums found: YES (/usr/bin/glib-mkenums)
Dependency gio-2.0 found: YES 2.78.3 (cached)
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Dependency gio-2.0 found: YES 2.78.3 (cached)
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Configuring wireplumber.service using configuration
Configuring wireplumber@.service using configuration
Program msgfmt found: YES (/usr/bin/msgfmt)
Program msginit found: YES (/usr/bin/msginit)
Program msgmerge found: YES (/usr/bin/msgmerge)
Program xgettext found: YES (/usr/bin/xgettext)
Program python3 (sphinx, sphinx_rtd_theme, breathe, sphinx.ext.graphviz) found: NO modules: sphinx, sphinx.ext.graphviz
Program python3 (lxml) found: YES (/usr/bin/python3) modules: lxml
Program doxygen found: YES 1.9.7 1.9.7 (/usr/bin/doxygen)
Program sphinx-build found: YES 6.2.1 6.2.1 (/usr/bin/sphinx-build)
Program g-ir-scanner found: NO
Program valgrind found: YES (/usr/bin/valgrind)
Message: Using glib.supp: /usr/share/glib-2.0/valgrind/glib.supp
Configuring wp-uninstalled.sh.in using configuration
Build targets in project: 121

wireplumber 0.5.2

    Lua version                    : 5.4.4 (built-in)
    systemd conf data              : YES
    libsystemd                     : YES
    libelogind                     : YES

  For documentation
    Python 3 Sphinx related modules: NO
    Doxygen                        : YES
    sphinx-build                   : YES

  For introspection
    Python 3 lxml module           : YES
    Doxygen                        : YES
    g-ir-scanner                   : NO

  Subprojects
    lua                            : YES

  User defined options
    prefix                         : /usr

Found ninja-1.11.1 at /usr/bin/ninja
Cleaning... 0 files.

**Comment by dxdye** [comment]
PS: I guess i need wireplumber to work in order to use pipewire. My pipewire service all day crashing.

**Comment by ford-prefect** [comment]
Hey @dxdye https://gitlab.freedesktop.org/pipewire/wireplumber/ is the place to track issues with WirePlumber. This mirror on GitHub is just for convenience. The error you see seems like you need a newer version of PipeWire.
