### ISSUE TITLE
wireplumber fails to compile

### ISSUE THREAD

**Issue by brobr** [PipeWire/wireplumber#4]
Hi, wireplumber does not compile at my end (on Slackware64-current).

Possibly on the documentation. But also with -Ddoc=disabled it stops with:
>[152/188] Compiling C object tests/wp/test-spa-pod.p/spa-pod.c.o
ninja: build stopped: subcommand failed.

build-trace here:
[lua-spa-pod.txt](https://github.com/PipeWire/wireplumber/files/7505552/lua-spa-pod.txt)

**Comment by ford-prefect** [comment]
@brobr this is just a mirror of the official repository. Please use [this link for WirePlumber issues](https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues).

**Comment by brobr** [comment]
On Tue, 09 Nov 2021 07:47:59 -0800
Arun Raghavan ***@***.***> wrote:

> @brobr this is just a mirror of the official repository. Please use
> [this link for WirePlumber
> issues](https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues).
> 

Ok, sorry.
