### ISSUE TITLE
wireplumber issue with fedora 35 on vm

### ISSUE THREAD

**Issue by Jamyka** [PipeWire/wireplumber#5]
Can anybody help me with this issue as i don't know what to do to have sound from my vm.

● wireplumber.service - Multimedia Service Session Manager
     Loaded: loaded (/usr/lib/systemd/user/wireplumber.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-12-26 16:26:32 EET; 19min ago
   Main PID: 5009 (wireplumber)
      Tasks: 4 (limit: 9440)
     Memory: 5.0M
        CPU: 77ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/wireplumber.service
             └─5009 /usr/bin/wireplumber

Dec 26 16:26:32 fedora systemd[1705]: Started Multimedia Service Session Manager.
Dec 26 16:26:32 fedora wireplumber[5009]: <WpPortalPermissionStorePlugin:0x56514ac45dc0> Failed to call Lookup: >
Dec 26 16:26:57 fedora wireplumber[5009]: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply

**Comment by pinkflames** [comment]
Allow me to quote a contributor:
> .. this is just a mirror of the official repository. Please use [this link for WirePlumber issues](https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues).

**Comment by AncientBlueFrog** [comment]
@Jamyka 
I had a similar problem after upgrading Fedora 35 on my pc.
I solved this by removing all files from `~/.local/state/wireplumber`, logging out and logging back in.
If that doesn't work, try creating a new account and replace the `~/.local/state/wireplumber` files with the `/home/YourNewAccount/.local/state/wireplumber` files.

**Comment by ford-prefect** [comment]
Closing this, please track on the upstream repo as @pinkflames points out.
