### ISSUE TITLE
0.4.9 breaks device selection on Fedora 35

### ISSUE THREAD

**Issue by MarcoWilli** [PipeWire/wireplumber#8]
With latest version I can not change any output(?) devices or better said the change does not get applied.
Reverting to previous version 0.4.4 everything works as intended.

Fedora 35 with standard Gnome.
Discussed this issue already on ask.fedora but I thought it would be important to report it directly.

**Comment by ford-prefect** [comment]
Hi, this is just a mirror and the official repository is at: https://gitlab.freedesktop.org/pipewire/pipewire/

If the problem isn't solved in 0.3.50, please raise an issue there. Thanks!
